#! /bin/sh
# /etc/init.d/dryonboot

### BEGIN INIT INFO
# Provides:          dryonboot
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script from www.stuffaboutcode.com which will start / st$
### END INIT INFO

# 1) Make script executable:
# sudo chmod 755 /etc/init.d/dryonboot

# 2) Register script to be run at start-up:
# sudo update-rc.d dryonboot defaults

# To remove script from start-up:
# sudo update-rc.d -f dryonboot remove

# To test starting the program:
# sudo /etc/init.d/dryonboot start

# To test stopping the program:
# sudo /etc/init.d/dryonboot stop

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
    start)
        echo "Starting RasPiDry"
        # run application you want to start
        python /var/www/RasPiDry/raspidry.py
    ;;
    stop)
        echo "Stopping RasPiDry"
        # kill application you want to stop
        killall python
        python /var/www/RasPiDry/cleanupGPIO.py
    ;;
*)
    echo "Usage: /etc/init.d/dryonboot {start|stop}"
    exit 1
    ;;
esac

exit 0